app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /api/

user:
    resource: "@UserBundle/Controller/"
    type: annotation
    prefix: /api/

customer:
    resource: "@CustomerBundle/Controller/"
    type: annotation
    prefix: /api/

ticket:
    resource: "@TicketBundle/Controller/"
    type: annotation
    prefix: /api/

rent:
    resource: "@RentBundle/Controller/"
    type: annotation
    prefix: /api/
