# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_provider:
            id: user.provider

    encoders:
        UserBundle\Entity\UserEntity: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            logout:
                path: /logout
                target: /
            simple_form:
                provider: user_provider
                authenticator: user.simple_authenticator
                login_path: login.simple_form
                check_path: login.simple_check
                success_handler: authentication_listener
                failure_handler: authentication_listener
