# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        # Описание ролей:
        # USER_MANAGEMENT - управление пользователями
        # ACCOUNT_MANAGEMENT - ответственный за арендаторов менеджер
        # RENT_MANAGEMENT - управление службой аренды
        # IT_MANAGEMENT - управление тикетной системой IT-поддержки
        # FINANCE_MANAGEMENT - управление тикетной системы Финансовой службы
        # MAINTAINCE_MANAGEMENT - управление тикетной системы службы эксплуатации
        # BOOKER_MANAGEMENT - управление тикетной системы SMART-бухгалтера
        # STORAGE_MANAGEMENT - управление складом
        # DOCUMENT_MANAGEMENT - управление документами
        # TICKET_ADMIN_MANAGEMENT - администратор тикетной системы
        # ROLE_INCOMING_CALLS_MANAGEMENT - получение входящих звонков на проходную
        # USER_CUSTOMER - управление собственными пользователями
        # IT_CUSTOMER - пользование IT-аутсорсингом (доступ опциональный по договору)
        # FINANCE_CUSTOMER - пользование тикетной системой финансовой службы
        # BOOKER_CUSTOMER - пользование услугой SMART-бухгалтер (доступ опциональный по договору)
        # MAINTAINCE_CUSTOMER - пользование тикетной системой службы эксплуатации
        # DOCUMENT_CUSTOMER - просмотр собственных документов
        # RENT_CUSTOMER - заказ в службе аренды
        # STORAGE_CUSTOMER - заказ на складе
        # ROLE_INCOMING_CALLS_CUSTOMER - получение входящих звонков от секретаря на проходной
        ROLE_SUPERADMIN:
            - ROLE_USER_MANAGEMENT
            - ROLE_RENT_MANAGEMENT
            - ROLE_STORAGE_MANAGEMENT
            - ROLE_DOCUMENT_MANAGEMENT
            - ROLE_IT_MANAGEMENT
            - ROLE_FINANCE_MANAGEMENT
            - ROLE_MAINTAINCE_MANAGEMENT
            - ROLE_BOOKER_MANAGEMENT
            - ROLE_TICKET_ADMIN_MANAGEMENT
            - ROLE_ACCOUNT_MANAGEMENT
            - ROLE_INCOMING_CALLS_MANAGEMENT
            - ROLE_SERVICE_MANAGEMENT

        ROLE_CUSTOMER_ADMIN:
            - ROLE_USER_CUSTOMER
            - ROLE_FINANCE_CUSTOMER
            - ROLE_MAINTAINCE_CUSTOMER
            - ROLE_DOCUMENT_CUSTOMER
            - ROLE_RENT_CUSTOMER
            - ROLE_STORAGE_CUSTOMER
            - ROLE_IT_CUSTOMER
            - ROLE_BOOKER_CUSTOMER
            - ROLE_INCOMING_CALLS_CUSTOMER
            - ROLE_SERVICE_CUSTOMER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_provider:
            entity:
                class: UserBundle:UserEntity
                property: email

        # доступ АТС для отправки входящих телефонных звонков
        ats:
            memory:
                users:
                    ats:
                        password: '%ats_password%'
                        roles: 'ROLE_ATS'


    encoders:
        UserBundle\Entity\UserEntity: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: ^/api/check_auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/profile/change_email/confirmation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/profile/change_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/remember_password/remember, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/change_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/incoming-call, roles: ROLE_ATS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # доступ для АТС-ки для получения входящих звонков
        ats_area:
            pattern: ^/api/incoming-call
            provider: ats
            anonymous: ~
            logout_on_user_change: true
            http_basic:
                realm: ''
                provider: ats

        main:
            pattern: ^/
            anonymous: ~
            provider: user_provider
            logout_on_user_change: true
            logout:
                path: /api/logout
                target: /
            form_login:
                login_path: login.simple_form
                check_path: login.simple_check
                success_handler: authentication_listener
                failure_handler: authentication_listener
#                always_use_default_target_path: false
