# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    json_error_response:
        class: HttpHelperBundle\Listener\JsonErrorResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # системный мейлер всего приложения
    mail_manager:
        class: AppBundle\Utils\MailManager
        arguments: [ '@mailer', '@templating', '%default_from_email%' ]

    # системные уведомления для пользователя в любой транспорт
    notification_manager:
        class: AppBundle\Utils\UserNotificationManager
        arguments: ['@doctrine.orm.entity_manager']
        calls:
            - [ 'setMailManager', ['@mail_manager'] ]
            - [ 'setCometClient', ['@comet_client'] ]
        tags:
            - { name: kernel.event_listener, event: 'user_notification', method: onUserNotification }

    # просмотр и управление системными уведомлениями для пользователя
    notification_controller:
        class: AppBundle\Controller\UserNotificationController
        arguments: ['@doctrine.orm.entity_manager', '@notification_manager']
        calls:
            - [ setContainer, ['@service_container'] ]

    # приём от АТС входящих звонков и переотправка арендаторам
    incoming_calls_controller:
        class: AppBundle\Controller\IncomingCallsController
        arguments: ['@user.roles_manager', '@doctrine.orm.entity_manager', '@event_dispatcher']
        calls:
            - [ setContainer, ['@service_container'] ]

    # клиент для подключения к comet-серверу
    comet_client:
        class: AppBundle\Service\CometClient
        arguments: ['%comet_url%']
