# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    json_error_response:
        class: HttpHelperBundle\Listener\JsonErrorResponseListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # системный мейлер всего приложения
    mail_manager:
        class: AppBundle\Utils\MailManager
        arguments: [ '@mailer', '@templating', '%default_from_email%' ]
