parameters:
    ticket.manager: 'TicketBundle\Utils\TicketManager'
    ticket.mailer: 'TicketBundle\Utils\TicketMailManager'
    ticket.voided_minutes: 10800 # количество минут, через которое закрыть отвеченную заявку
    ticket.ticket_controller: 'TicketBundle\Controller\TicketController'
    ticket.category_voter: 'TicketBundle\Security\TicketCategoryVoter'
    ticket.ticket_voter: 'TicketBundle\Security\TicketVoter'

services:
    # API для управления заявками и сообщениями
    ticket.manager:
        class: '%ticket.manager%'
        arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher', '%ticket.voided_minutes%']

    # API для управления писем по заявкам
    ticket.mailer:
        class: '%ticket.mailer%'
        arguments: ['@mail_manager', '@doctrine.orm.entity_manager', '@user.roles_manager']
        tags:
            - { name: kernel.event_subscriber }

    # контроллер для работы с тикетами
    ticket.ticket_controller:
        class: '%ticket.ticket_controller%'
        arguments: [ '@ticket.manager', '@user.roles_manager', '@doctrine.orm.entity_manager' ]
        calls:
            - [ setContainer, ['@service_container'] ]

    # проверка прав доступа к категории тикетов
    ticket.category_voter:
        class: '%ticket.category_voter%'
        arguments: [ '@security.access.decision_manager' ]
        public: false
        tags:
            - { name: security.voter }

    # проверка прав доступа к тикетов
    ticket.ticket_voter:
        class: '%ticket.ticket_voter%'
        arguments: [ '@security.access.decision_manager' ]
        public: false
        tags:
            - { name: security.voter }
