parameters:
    customer.customer_manager_controller: CustomerBundle\Controller\CustomerManagerController
    customer.customer_voter: CustomerBundle\Security\CustomerVoter
    customer.service_manager_controller: CustomerBundle\Controller\ServiceManagerController

services:
    # Администраторское управление дополнительными услугами
    customer.service_manager_controller:
        class: '%customer.service_manager_controller%'
        arguments: ['@doctrine.orm.entity_manager']
        calls:
            - [ setContainer, [ '@service_container' ] ]

    # Администраторское управление контрагентами
    customer.customer_manager_controller:
        class: '%customer.customer_manager_controller%'
        arguments: ['@doctrine.orm.entity_manager']
        calls:
            - [ setContainer, [ '@service_container' ] ]

    # проверка права доступа для пользователей
    customer.customer_voter:
        class: '%customer.customer_voter%'
        tags:
            - { name: security.voter }
